---
- name: Download WordPress
  get_url: url=https://ja.wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz

- name: Copy WordPress directory
  command: /usr/bin/rsync -a /srv/wordpress/  /var/www/html/ creates=/var/www/html/index.php

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/var/www/html/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  become_method: sudo

- name: Create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    login_host: "{{ wp_db_login_host }}"
    login_user: "{{ wp_db_login_user }}"
    login_password: "{{ wp_db_login_password }}"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    login_host: "{{ wp_db_login_host }}"
    login_user: "{{ wp_db_login_user }}"
    login_password: "{{ wp_db_login_password }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: '%'
    state: present

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/html/
  notify: restart nginx

- name: Change ownership of WordPress installation
  file: path=/var/www/html/ owner=nginx group=nginx state=directory recurse=yes

- name: Start php70-fpm Service
  service: name=php-fpm-7.0 state=started enabled=yes
