---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - php70
    - php70-fpm
    - php70-gd
    - php70-mbstring
    - php70-mcrypt
    - php70-mysqlnd
    - php70-zip
    #- php-enchant
    #- php-IDNA_Convert
    #- php-mysql
    #- php-PHPMailer
    #- php-process
    #- php-simplepie
    #- php-xml



#- name: Disable default pool
#  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
#  notify: restart php-fpm

- name: Copy php-7.0.ini configuration
  template: src=php-7.0.conf.j2 dest=/etc/php-7.0.ini
  notify: restart php-fpm-7.0

- name: Copy php70-fpm configuration
  file: src=www.conf.j2 dest=/etc/php-fpm-7.0.d/www.conf
  notify: restart php-fpm-7.0

- name: Set Owner
  file: path=/var/lib/php/7.0/session owner=nginx group=nginx state=directory recurse=yes

- name: Auto Start php70-fpm
  service: name=php-fpm-7.0 state=started enabled=yes
